### ISSUE TITLE
[QUESTION]can i get GUID of ifc file？

### ISSUE THREAD

**Issue by slim1551** [helpsterTee/Unity-IFCEngine#3] opened 2018-08-15 08:02 UTC
I hope to get the GUID information of the model.But I don't know if this project can be done.Or is there any other way to get a GUID?Is such a message:
![image](https://user-images.githubusercontent.com/39392690/44137780-3bf003f6-a0a4-11e8-9326-d6b1070fc38e.png)
Could you tell me how to solve it?please

**Comment by slim1551** [comment] 2018-08-15 08:25
and is there a .dll document ? Many interfaces don't know what it does. last, thank you for sharing . This is very helpful to me.

**Comment by helpsterTee** [comment] 2018-12-10 17:12
Not with the current implementation, I will switch to XBim in 2019 to have support for GUIDs

**Comment by helpsterTee** [comment] 2019-03-07 10:38
Duplicate of #6 
Please check there

**Closed** 2019-03-07 10:38 UTC
